# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgsl-dev libgsl23 libgslcblas0


matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel

