---
title: "Bivariate mappings of cluster traits"
author: "Frederick J. Boehm"
date: "3/23/2020"
output: html_document
---

```{r setup2, include=FALSE, dev="CairoPNG"}
.libPaths("~/work/libs")
knitr::opts_chunk$set(dev="CairoPNG")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read the csv files

```{r}
cluster_traits <- readr::read_csv("../data/pheno_eigenscores_from_WGCNA_all60_win.csv")
```
```{r}
load("../data/reduced_map_qtl2_mapping_objects.Rdata")
kinship <- qtl2::calc_kinship(probs = genoprobs.1, type = "loco")
```

```{r}
phe <- as.matrix(cluster_traits[, c("greenyellow", "magenta")])
rownames(phe) <- cluster_traits$X1
start <- max(which(map.1$`10` < 20)) 
end <- min(which(map.1$`10` > 45))
```

```{r}
library(magrittr)
```

## Pairwise analyses of greenyellow and magenta

```{r}
sp_out <- qtl2pleio::scan_pvl(probs = genoprobs.1$`10`, 
                                pheno = phe,
                                kinship = kinship$`10`,
                                addcovar = addcovar, 
                                start_snp = start,
                                n_snp = end - start + 1, 
                                n_cores = parallel::detectCores() - 1
                                )
(lrt <- qtl2pleio::calc_lrt_tib(sp_out))
```

```{r}
sp_out %>%
  qtl2pleio::calc_profile_lods() %>%
  qtl2pleio::add_pmap(pmap = map.1$`10`) %>%
  ggplot2::ggplot() + ggplot2::geom_line(ggplot2::aes(x = marker_position, y = profile_lod, colour = trait))
```

```{r}
(pp_index <- qtl2pleio::find_pleio_peak_tib(tib = sp_out, 
                                           start_snp = start
                                           ))
```

```{r}
map.1$`10`[pp_index]
```


