---
title: "Bivariate mappings for CC study"
author: "Frederick J. Boehm"
date: "3/23/2020"
output: html_document
---

```{r setup2, include=FALSE, dev="CairoPNG"}
knitr::opts_chunk$set(dev="CairoPNG")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read the csv files

```{r}
cluster_traits <- readr::read_csv("../data/pheno_eigenscores_from_WGCNA_all60_win.csv")
```


```{r}
load("../data/reduced_map_qtl2_mapping_objects.Rdata")
kinship <- qtl2::calc_kinship(probs = genoprobs.1, type = "loco")
```

```{r}
phe <- as.matrix(cluster_traits[, c("greenyellow", "magenta")])
rownames(phe) <- cluster_traits$X1
start <- max(which(map.1$`10` < 20)) 
end <- min(which(map.1$`10` > 45))
```

```{r}
library(magrittr)
library(ggplot2)
```

## WCGNA traits 





```{r, scan_pvl}
spfn <- "../data/bivariate-greenyellow-magenta-Chr10.rds"
if (!file.exists(spfn)){
  sp_out <- qtl2pleio::scan_pvl(probs = genoprobs.1$`10`, 
                                pheno = phe,
                                kinship = kinship$`10`,
                                start_snp = start,
                                n_snp = end - start + 1
                                )
  saveRDS(sp_out, file = spfn)

} else {sp_out <- readRDS(spfn)}
(lrt <- qtl2pleio::calc_lrt_tib(sp_out))
```

```{r, plot}
sp_out %>%
  qtl2pleio::calc_profile_lods() %>%
  qtl2pleio::add_pmap(pmap = map.1$`10`) %>%
  ggplot2::ggplot() + ggplot2::geom_line(ggplot2::aes(x = marker_position, y = profile_lod, colour = trait))
```



```{r, future_setup}
library(future.batchtools)
library(future)
options(future.globals.maxSize= 4 * 1024 ^ 3)
#plan(list(tweak(batchtools_lsf, template = "~/.lsf.tmpl"), 
#          multiprocess)
#     )
plan(batchtools_multicore, workers = 32)
```



```{r, boot}
bfn <- "../data/bivariate-greenyellow-magenta-Chr10-boot.rds"

if (!file.exists(bfn)){
  (pp_index <- qtl2pleio::find_pleio_peak_tib(tib = sp_out, 
                                             start_snp = start
                                             ))
  set.seed(3411192)
  b_out <- qtl2pleio::boot_pvl(probs = genoprobs.1$`10`, 
                      pheno = phe,
                      kinship = kinship$`10`,
                      start_snp = start,
                      n_snp = end - start + 1, 
                      pleio_peak_index = pp_index,
                      nboot = 400
                     )
  saveRDS(b_out, file = bfn)
} else {b_out <- readRDS(bfn)}
(pvalue <- mean(b_out >= lrt))
```

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
if ("devtools" %in% installed.packages()) devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? 
if ("git2r" %in% installed.packages() & git2r::in_repository(path = ".")) git2r::repository(here::here())  
```


